-- 코드를 입력하세요
# JOIN KEY = PRODUCT_ID
# 상품 코드 p.PRODUCT_CODE
SELECT
 p.PRODUCT_CODE,
 SUM(p.PRICE * o.SALES_AMOUNT) AS PRICE
 # 상품코드 별 매출액(판매가 * 판매량) 합계
FROM
 PRODUCT AS p
LEFT JOIN
 OFFLINE_SALE AS o
ON
p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY
 p.PRODUCT_CODE
ORDER BY
 PRICE DESC, p.PRODUCT_CODE
