-- 코드를 작성해주세요
SELECT
 COUNT(i.ID) AS FISH_COUNT,
 n.FISH_NAME AS FISH_NAME
FROM
 FISH_NAME_INFO AS n
INNER JOIN 
 FISH_INFO AS i
ON 
 n.FISH_TYPE = i.FISH_TYPE
GROUP BY
 n.FISH_NAME
ORDER BY
 FISH_COUNT DESC